name: 03 - Workflow Runners
on: push

jobs:
  ubuntu-echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show OS
        run: echo "This job is running on Ubuntu runner"

  window-echo:
    runs-on: windows-latest
    steps:
      - name: Show OS
        run: echo "This job is running on Windows runner"

  mac-echo:
    runs-on: windows-latest
    steps:
      - name: Show OS
        run: echo "This job is running on Mac runner"
